[package]
name = "types3"
version = "0.1.0"
authors = ["Jukka Suomela"]
edition = "2021"
description = "Type accumulation curves"
license = "MIT"
readme = "README.md"
repository = "https://github.com/suomela/types3"
default-run = "types3"

[dependencies]
clap = { version = "4.3.10", features = ["derive"] }
console = "0.15.7"
crossbeam-channel = "0.5.8"
indicatif = "0.17.5"
itertools = "0.11.0"
num_cpus = "1.16.0"
rand = "0.8.5"
rand_xoshiro = "0.6.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.99"
