[package]
name = "types3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.5.8"
density-curve = { version = "0.1.0", path = "../density-curve" }
itertools = "0.11.0"
num_cpus = "1.16.0"
