mod calc_avg;
mod calc_point;
mod calculation;
pub mod categories;
mod counter;
pub mod driver;
pub mod errors;
mod information;
pub mod input;
pub mod output;
mod parallelism;
mod samples;
mod shuffle;
mod subsets;
